name: Cowboy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Node Build
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
      - run: npm run clean
      - run: npm run build

      # COWBOY
      - name: Deploy
        uses: "appleboy/scp-action@master"
        with:
          host: ${{ secrets.COWBOY_HOST }}
          port: 22
          username: ${{ secrets.COWBOY_USER }}
          key: ${{ secrets.COWBOY_KEY }}
          source: "dist/*"
          target: /srv/handy/src/pmx/creative
          overwrite: true
