name: Cowboy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build
        run: pnpm run clean && pnpm run build

      - name: Deploy to Cowboy
        uses: "appleboy/scp-action@master"
        with:
          host: ${{ secrets.COWBOY_HOST }}
          port: 22
          username: ${{ secrets.COWBOY_USER }}
          key: ${{ secrets.COWBOY_KEY }}
          source: "dist/*"
          target: /srv/handy/src/pmx/creative
          overwrite: true
